#! /usr/bin/env bash

cd "$(dirname "$0")"

MACRO_PREFIX="m4_"
MACRO_SUFFIX="_char"
OUTPUT_FILE="chars.m4"

echo -e "# DO NOT EDIT THIS FILE WITH A TEXT EDITOR" > "${OUTPUT_FILE}"

declare -A pairs=( ["escape"]="e" ["tab"]="t" ["newline"]="n" ["carriage_return"]="r" ["form_feed"]="f" ["backspace"]="b" ["alert"]="a" ["vertical_tab"]="v" )

for NAME in "${!pairs[@]}"; do
  ESCAPE_CHAR=${pairs[$NAME]}
  MACRO_NAME="${MACRO_PREFIX}${NAME}${MACRO_SUFFIX}"
  MACRO_VALUE="\\${ESCAPE_CHAR}"

  echo "${MACRO_NAME} = ${MACRO_VALUE}"
  echo -e "m4_define([${MACRO_NAME}], [${MACRO_VALUE}])" >> "${OUTPUT_FILE}"
done

echo -en "m4_define([m4_char], [m4_case([\$1]" >> "${OUTPUT_FILE}"

for NAME in "${!pairs[@]}"; do
  ESCAPE_CHAR=${pairs[$NAME]}
  echo -en ", [${ESCAPE_CHAR}], [\\${ESCAPE_CHAR}]" >> "${OUTPUT_FILE}"
done

echo -en ")])\n" >> "${OUTPUT_FILE}"
