# DO NOT EDIT THIS FILE WITH A TEXT EDITOR
m4_define([m4_vertical_tab_char], [])
m4_define([m4_alert_char], [])
m4_define([m4_carriage_return_char], [])
m4_define([m4_tab_char], [	])
m4_define([m4_backspace_char], [])
m4_define([m4_form_feed_char], [])
m4_define([m4_escape_char], [])
m4_define([m4_newline_char], [
])
m4_define([m4_char], [m4_case([$1], [v], [], [a], [], [r], [], [t], [	], [b], [], [f], [], [e], [], [n], [
])])
